// <auto-generated />
using System;
using EF.CodeFirst.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.CodeFirst.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210208083343_createDb")]
    partial class createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EF.CodeFirst.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Employee", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("NationalIdNumber")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationNode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("BusinessEntityId");

                    b.HasIndex("PersonId");

                    b.HasIndex("NationalIdNumber", "LoginId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.EmployeeDepartment", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId", "DepartmentId", "ShiftId", "StartDate");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ShiftId");

                    b.ToTable("EmployeeDepartment");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.EmployeePayHistory", b =>
                {
                    b.Property<DateTime>("RateChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeBusinessEntityId")
                        .HasColumnType("int");

                    b.Property<float>("PayFrequency")
                        .HasColumnType("real");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.HasKey("RateChangeDate");

                    b.HasIndex("EmployeeBusinessEntityId");

                    b.ToTable("EmployeePayHistories");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.JobCandidate", b =>
                {
                    b.Property<int>("JobCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BusinessEntityId1")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCandidateId");

                    b.HasIndex("BusinessEntityId1");

                    b.ToTable("JobCandidates");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.SalesPerson", b =>
                {
                    b.Property<int>("BusinessEntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("EmployeeBusinessEntityId")
                        .HasColumnType("int");

                    b.Property<string>("SalesQuota")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BusinessEntityId");

                    b.HasIndex("EmployeeBusinessEntityId");

                    b.ToTable("SalesPersons");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.HasIndex("Name", "StartTime", "EndTime")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Employee", b =>
                {
                    b.HasOne("EF.CodeFirst.Entities.Person", "Person")
                        .WithMany("Employees")
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.EmployeeDepartment", b =>
                {
                    b.HasOne("EF.CodeFirst.Entities.Department", "Department")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.CodeFirst.Entities.Employee", "Employee")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF.CodeFirst.Entities.Shift", "Shift")
                        .WithMany("EmployeeDepartments")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.EmployeePayHistory", b =>
                {
                    b.HasOne("EF.CodeFirst.Entities.Employee", "Employee")
                        .WithMany("EmployeePayHistories")
                        .HasForeignKey("EmployeeBusinessEntityId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.JobCandidate", b =>
                {
                    b.HasOne("EF.CodeFirst.Entities.Employee", "BusinessEntityId")
                        .WithMany("JobCandidates")
                        .HasForeignKey("BusinessEntityId1");

                    b.Navigation("BusinessEntityId");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.SalesPerson", b =>
                {
                    b.HasOne("EF.CodeFirst.Entities.Employee", "Employee")
                        .WithMany("SalesPersons")
                        .HasForeignKey("EmployeeBusinessEntityId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Department", b =>
                {
                    b.Navigation("EmployeeDepartments");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeDepartments");

                    b.Navigation("EmployeePayHistories");

                    b.Navigation("JobCandidates");

                    b.Navigation("SalesPersons");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Person", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EF.CodeFirst.Entities.Shift", b =>
                {
                    b.Navigation("EmployeeDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
